### PR TITLE
Numbox improve (fix #246)

### LINKED ISSUE #246: Value of ONE_SCROLL is not universal (NumericBox widget)
**Describe the bug**
In source of `NumericBox` widget, value of `ONE_SCROLL` is not universal between systems, thus value inside of `NumericBox` may not be changed by multiples of `step`.

**To Reproduce**
1. `cargo run --example numeric_box`
2. Scroll with mouse wheel on numeric box
3. You may or not see the bug

**Expected behavior**
Value inside of `NumericBox` should be multiple of declared step. On my system it clearly isn't.
Also precision should be adjusted to size of the widget.

**Screenshots**
screen

**Desktop**
 - OS: Windows 10 v1909 (Fedora for WSL and Lubuntu on Virtualbox)
 - Version v0.3.1-alpha3

**Additional context**
I changed value of "how many lines to scroll each time" in Windows Settings and it doesn't seem to be connected to it.
Maybe it is something with mouse driver?

### PR DESCRIPTION
**Pull request by kivimango**
Fixes #246.
Added ActivateHandler and ChangedHandler suggested by @rzerres.
Values clamped to boundaries suggested by @michalsieron.

### CODE REVIEW

File: crates/widgets/src/numeric_box.rs [hunk 1]
```diff
@@ -19,13 +17,13 @@ enum InputAction {
 }
 
 #[derive(Default, AsAny)]
-struct NumericBoxState {
-    action: Option<InputAction>,
+pub struct NumericBoxState {
```
Comment (FloVanGH) [inline crates/widgets/src/numeric_box.rs:20]: @kivimango why do it all public?

Comment (kivimango) [reply crates/widgets/src/numeric_box.rs:20]: In case of anyone needs some fields from the State struct in the callbacks where there is no Context available.

Comment (FloVanGH) [reply crates/widgets/src/numeric_box.rs:20]: Ok.

**Comment by FloVanGH** [comment]
Great thank you.
